import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import type { Report } from '../types/report';
import type { Invoice } from '../types/client';
import type { Lead, Contact, TokenUsage, Client } from '../types/aios';
import logoSrc from '../assets/neura-logo-white.png';

const _logoImg = new Promise<HTMLImageElement>((resolve) => {
  const img = new Image();
  img.onload = () => resolve(img);
  img.onerror = () => resolve(new Image());
  img.src = logoSrc;
});

const BRAND_HEX = '#6366f1';
const BRAND_RGB: [number, number, number] = [99, 102, 241];
const SURFACE_RGB: [number, number, number] = [248, 250, 252];
const TEXT_DARK_HEX = '#0f172a';
const TEXT_MID_HEX = '#64748b';
const TEXT_LIGHT_HEX = '#94a3b8';

const SOURCE_LABEL: Record<string, string> = {
  website: 'Website',
  linkedin: 'LinkedIn',
  referral: 'Referral',
  ads: 'Ads',
  other: 'Other',
};

async function addPageHeader(doc: jsPDF, title: string, meta?: string): Promise<number> {
  const w = doc.internal.pageSize.getWidth();

  doc.setFillColor(BRAND_HEX);
  doc.rect(0, 0, w, 30, 'F');

  const logo = await _logoImg;
  if (logo.naturalWidth > 0) {
    const logoH = 18;
    const logoW = (logo.naturalWidth / logo.naturalHeight) * logoH;
    doc.addImage(logo, 'PNG', 12, 6, logoW, logoH);
  }

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9);
  doc.setTextColor(255, 255, 255);
  doc.text('NeuraSolutions', w - 14, 13, { align: 'right' });

  if (meta) {
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(7.5);
    doc.setTextColor(200, 200, 255);
    doc.text(meta, w - 14, 20, { align: 'right' });
  }

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(17);
  doc.setTextColor(TEXT_DARK_HEX);
  doc.text(title, 14, 46);

  return 52;
}

function addPageFooters(doc: jsPDF): void {
  const pageCount = doc.getNumberOfPages();
  const w = doc.internal.pageSize.getWidth();
  const h = doc.internal.pageSize.getHeight();
  const today = new Date().toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' });

  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setDrawColor(220, 220, 220);
    doc.line(14, h - 14, w - 14, h - 14);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(7.5);
    doc.setTextColor(TEXT_LIGHT_HEX);
    doc.text(`Generated by NeuraSolutions AIOS · ${today}`, 14, h - 7);
    doc.text(`Page ${i} / ${pageCount}`, w - 14, h - 7, { align: 'right' });
  }
}

// ── Reports ────────────────────────────────────────────────────────────────

export async function downloadReportPDF(report: Report): Promise<void> {
  const doc = new jsPDF();
  const w = doc.internal.pageSize.getWidth();

  const meta = `${report.period} · ${report.type.charAt(0).toUpperCase() + report.type.slice(1)} Report`;
  let y = await addPageHeader(doc, report.title, meta);

  // Category badge
  const catLabel = report.category.replace(/-/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase());
  doc.setFillColor('#e0e7ff');
  doc.roundedRect(14, y, catLabel.length * 4 + 16, 8, 2, 2, 'F');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(7);
  doc.setTextColor(BRAND_HEX);
  doc.text(catLabel.toUpperCase(), 14 + (catLabel.length * 4 + 16) / 2, y + 5.5, { align: 'center' });

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.setTextColor(TEXT_MID_HEX);
  const genDate = new Date(report.generatedAt).toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' });
  doc.text(`Generated: ${genDate}  ·  ${report.size}`, w - 14, y + 5.5, { align: 'right' });

  y += 16;
  doc.setDrawColor(230, 230, 230);
  doc.line(14, y, w - 14, y);
  y += 10;

  // Summary
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  doc.setTextColor(TEXT_DARK_HEX);
  doc.text('Summary', 14, y);
  y += 6;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8.5);
  doc.setTextColor(TEXT_MID_HEX);
  const summaryLines = doc.splitTextToSize(report.summary, w - 28) as string[];
  doc.text(summaryLines, 14, y);
  y += summaryLines.length * 5 + 10;

  // Highlights
  if (report.highlights.length > 0) {
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(10);
    doc.setTextColor(TEXT_DARK_HEX);
    doc.text('Key Highlights', 14, y);
    y += 7;

    report.highlights.forEach((h) => {
      doc.setFillColor(BRAND_HEX);
      doc.circle(17.5, y - 1.5, 1.5, 'F');
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(8.5);
      doc.setTextColor(TEXT_MID_HEX);
      doc.text(h, 22, y);
      y += 6;
    });
    y += 6;
  }

  // AI Insight box
  const noteLines = doc.splitTextToSize(report.aiGeneratedNote, w - 44) as string[];
  const boxH = noteLines.length * 5 + 18;
  doc.setFillColor('#eef2ff');
  doc.roundedRect(14, y, w - 28, boxH, 4, 4, 'F');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(7.5);
  doc.setTextColor(BRAND_HEX);
  doc.text('✦  AI INSIGHT', 20, y + 9);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8.5);
  doc.setTextColor('#3730a3');
  doc.text(noteLines, 20, y + 16);

  addPageFooters(doc);
  doc.save(`${report.title.replace(/[\s/]+/g, '-')}.pdf`);
}

// ── Invoices ───────────────────────────────────────────────────────────────

export async function downloadInvoicePDF(invoice: Invoice): Promise<void> {
  const doc = new jsPDF();
  const w = doc.internal.pageSize.getWidth();

  const dueFormatted = new Date(invoice.dueDate).toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' });
  let y = await addPageHeader(doc, `Invoice ${invoice.number}`, `Due: ${dueFormatted}`);

  // Status badge
  const statusStyle: Record<string, { bg: string; text: string }> = {
    paid:    { bg: '#d1fae5', text: '#065f46' },
    pending: { bg: '#fef3c7', text: '#92400e' },
    overdue: { bg: '#fee2e2', text: '#991b1b' },
  };
  const style = statusStyle[invoice.status] ?? { bg: '#f1f5f9', text: '#475569' };

  doc.setFillColor(style.bg);
  doc.roundedRect(14, y, 32, 8, 2, 2, 'F');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(7.5);
  doc.setTextColor(style.text);
  doc.text(invoice.status.toUpperCase(), 30, y + 5.5, { align: 'center' });

  y += 16;
  doc.setDrawColor(225, 225, 225);
  doc.line(14, y, w - 14, y);
  y += 10;

  // Details grid
  const half = w / 2;
  const drawDetail = (label: string, value: string, x: number, offsetY: number) => {
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(7);
    doc.setTextColor(TEXT_LIGHT_HEX);
    doc.text(label.toUpperCase(), x, offsetY);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.setTextColor(TEXT_DARK_HEX);
    doc.text(value, x, offsetY + 7);
  };

  const invDate = new Date(invoice.date).toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' });
  drawDetail('Invoice Number', invoice.number, 14, y);
  drawDetail('Invoice Date', invDate, half, y);
  y += 18;

  drawDetail('Bill To', 'Atlas Ventures', 14, y);
  drawDetail('Due Date', dueFormatted, half, y);
  y += 18;

  doc.line(14, y, w - 14, y);
  y += 6;

  // Line items
  const rows =
    invoice.items.length > 0
      ? invoice.items.map((item) => [
          item.description,
          String(item.quantity),
          `£${item.unitPrice.toLocaleString('en-GB', { minimumFractionDigits: 2 })}`,
          `£${item.total.toLocaleString('en-GB', { minimumFractionDigits: 2 })}`,
        ])
      : [['NeuraSolutions AIOS — Professional Plan', '1',
          `£${invoice.amount.toLocaleString('en-GB', { minimumFractionDigits: 2 })}`,
          `£${invoice.amount.toLocaleString('en-GB', { minimumFractionDigits: 2 })}`]];

  autoTable(doc, {
    startY: y,
    head: [['Description', 'Qty', 'Unit Price', 'Total']],
    body: rows,
    headStyles: { fillColor: BRAND_RGB, textColor: [255, 255, 255], fontSize: 9, fontStyle: 'bold' },
    bodyStyles: { fontSize: 9, textColor: [15, 23, 42] },
    alternateRowStyles: { fillColor: SURFACE_RGB },
    columnStyles: {
      0: { cellWidth: 'auto' },
      1: { cellWidth: 18, halign: 'center' },
      2: { cellWidth: 38, halign: 'right' },
      3: { cellWidth: 38, halign: 'right', fontStyle: 'bold' },
    },
    margin: { left: 14, right: 14 },
  });

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const tableEndY: number = (doc as any).lastAutoTable.finalY + 8;
  const totalW = 82;

  doc.setFillColor('#f8fafc');
  doc.roundedRect(w - 14 - totalW, tableEndY, totalW, 22, 3, 3, 'F');
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8.5);
  doc.setTextColor(TEXT_MID_HEX);
  doc.text('Total Due', w - 14 - totalW + 8, tableEndY + 9);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(15);
  doc.setTextColor(BRAND_HEX);
  doc.text(`£${invoice.amount.toLocaleString('en-GB', { minimumFractionDigits: 2 })}`, w - 16, tableEndY + 16, { align: 'right' });

  addPageFooters(doc);
  doc.save(`${invoice.number}.pdf`);
}

// ── Leads ──────────────────────────────────────────────────────────────────

export async function downloadLeadsPDF(leads: Lead[], statusFilter: string, search: string): Promise<void> {
  const doc = new jsPDF({ orientation: 'landscape' });

  const filterDesc = [
    statusFilter !== 'all' ? `Status: ${statusFilter}` : 'All statuses',
    search ? `Search: "${search}"` : null,
  ]
    .filter(Boolean)
    .join(' · ');

  let y = await addPageHeader(doc, 'Leads Report', `${leads.length} leads · ${filterDesc}`);
  y += 4;

  const STATUS_COLOR: Record<string, [number, number, number]> = {
    new:       [59, 130, 246],
    contacted: [245, 158, 11],
    qualified: [99, 102, 241],
    won:       [16, 185, 129],
    lost:      [239, 68, 68],
  };

  autoTable(doc, {
    startY: y,
    head: [['Name', 'Email', 'Phone', 'Source', 'Status', 'Score', 'Added']],
    body: leads.map((l) => [
      l.name,
      l.email,
      l.phone ?? '—',
      SOURCE_LABEL[l.source] ?? l.source,
      l.status.charAt(0).toUpperCase() + l.status.slice(1),
      `${l.score}%`,
      new Date(l.created_at).toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' }),
    ]),
    headStyles: { fillColor: BRAND_RGB, textColor: [255, 255, 255], fontSize: 9, fontStyle: 'bold' },
    bodyStyles: { fontSize: 8.5, textColor: [15, 23, 42] },
    alternateRowStyles: { fillColor: SURFACE_RGB },
    columnStyles: {
      0: { cellWidth: 45 },
      1: { cellWidth: 62 },
      2: { cellWidth: 32 },
      3: { cellWidth: 28 },
      4: { cellWidth: 28 },
      5: { cellWidth: 20, halign: 'center' },
      6: { cellWidth: 32 },
    },
    didParseCell(data) {
      if (data.section === 'body' && data.column.index === 4) {
        const lead = leads[data.row.index];
        if (lead && STATUS_COLOR[lead.status]) {
          data.cell.styles.textColor = STATUS_COLOR[lead.status];
          data.cell.styles.fontStyle = 'bold';
        }
      }
    },
    margin: { left: 14, right: 14 },
  });

  addPageFooters(doc);
  doc.save(`leads-report-${new Date().toISOString().slice(0, 10)}.pdf`);
}

// ── Contacts ───────────────────────────────────────────────────────────────

export async function downloadContactsPDF(contacts: Contact[], statusFilter: string, search: string): Promise<void> {
  const doc = new jsPDF({ orientation: 'landscape' });

  const filterDesc = [
    statusFilter !== 'all' ? `Status: ${statusFilter}` : 'All statuses',
    search ? `Search: "${search}"` : null,
  ]
    .filter(Boolean)
    .join(' · ');

  let y = await addPageHeader(doc, 'CRM Contacts Report', `${contacts.length} contacts · ${filterDesc}`);
  y += 4;

  autoTable(doc, {
    startY: y,
    head: [['Name', 'Email', 'Company', 'Phone', 'Status', 'Added']],
    body: contacts.map((c) => [
      c.name,
      c.email,
      c.company ?? '—',
      c.phone ?? '—',
      c.status === 'active' ? 'Active' : 'Inactive',
      new Date(c.created_at).toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' }),
    ]),
    headStyles: { fillColor: BRAND_RGB, textColor: [255, 255, 255], fontSize: 9, fontStyle: 'bold' },
    bodyStyles: { fontSize: 8.5, textColor: [15, 23, 42] },
    alternateRowStyles: { fillColor: SURFACE_RGB },
    columnStyles: {
      0: { cellWidth: 48 },
      1: { cellWidth: 65 },
      2: { cellWidth: 55 },
      3: { cellWidth: 38 },
      4: { cellWidth: 28 },
      5: { cellWidth: 38 },
    },
    didParseCell(data) {
      if (data.section === 'body' && data.column.index === 4) {
        const contact = contacts[data.row.index];
        if (contact) {
          data.cell.styles.textColor =
            contact.status === 'active' ? [16, 185, 129] : [100, 116, 139];
          data.cell.styles.fontStyle = 'bold';
        }
      }
    },
    margin: { left: 14, right: 14 },
  });

  addPageFooters(doc);
  doc.save(`contacts-report-${new Date().toISOString().slice(0, 10)}.pdf`);
}

// ── Usage ──────────────────────────────────────────────────────────────────

export async function downloadUsagePDF(rows: TokenUsage[], agentFilter: string): Promise<void> {
  const doc = new jsPDF({ orientation: 'landscape', unit: 'mm', format: 'a4' });
  const y = await addPageHeader(
    doc,
    'Usage & Tokens Report',
    agentFilter ? `Agent: ${agentFilter}` : 'All Agents'
  );

  const totalCost = rows.reduce((s, r) => s + r.cost, 0);
  const totalTokens = rows.reduce((s, r) => s + r.tokens_in + r.tokens_out, 0);

  doc.setFontSize(10);
  doc.setTextColor(TEXT_MID_HEX);
  doc.text(
    `Total records: ${rows.length}   |   Total tokens: ${totalTokens.toLocaleString()}   |   Total cost: £${(totalCost * 0.79).toFixed(4)}`,
    14,
    y + 8
  );

  autoTable(doc, {
    startY: y + 14,
    head: [['Agent', 'Model', 'Tokens In', 'Tokens Out', 'Cost (£)', 'Date']],
    body: rows.map((r) => [
      r.agent_name,
      r.model,
      r.tokens_in.toLocaleString(),
      r.tokens_out.toLocaleString(),
      `£${(r.cost * 0.79).toFixed(4)}`,
      new Date(r.created_at).toLocaleDateString('en-GB', {
        year: 'numeric',
        month: 'short',
        day: 'numeric',
      }),
    ]),
    styles: { fontSize: 9, cellPadding: 3 },
    headStyles: { fillColor: BRAND_RGB, textColor: [255, 255, 255], fontStyle: 'bold' },
    alternateRowStyles: { fillColor: SURFACE_RGB },
    margin: { left: 14, right: 14 },
  });

  addPageFooters(doc);
  doc.save(`usage-report-${new Date().toISOString().slice(0, 10)}.pdf`);
}

// ── Clients ────────────────────────────────────────────────────────────────

export async function downloadClientsPDF(clients: Client[], statusFilter: string, search: string): Promise<void> {
  const doc = new jsPDF({ orientation: 'landscape' });

  const filterDesc = [
    statusFilter !== 'all' ? `Status: ${statusFilter}` : 'All statuses',
    search ? `Search: "${search}"` : null,
  ]
    .filter(Boolean)
    .join(' · ');

  let y = await addPageHeader(doc, 'Clients Report', `${clients.length} clients · ${filterDesc}`);
  y += 4;

  const STATUS_COLOR: Record<string, [number, number, number]> = {
    active:   [16, 185, 129],
    inactive: [245, 158, 11],
    churned:  [239, 68, 68],
  };

  autoTable(doc, {
    startY: y,
    head: [['Company', 'Name', 'Email', 'Contract Value', 'Status', 'Renewal']],
    body: clients.map((c) => [
      c.company,
      c.name,
      c.email,
      c.contract_value != null
        ? `£${c.contract_value.toLocaleString('en-GB', { minimumFractionDigits: 2 })}`
        : '—',
      c.status.charAt(0).toUpperCase() + c.status.slice(1),
      c.next_renewal_at
        ? new Date(c.next_renewal_at + 'T00:00:00').toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' })
        : '—',
    ]),
    headStyles: { fillColor: BRAND_RGB, textColor: [255, 255, 255], fontSize: 9, fontStyle: 'bold' },
    bodyStyles: { fontSize: 8.5, textColor: [15, 23, 42] },
    alternateRowStyles: { fillColor: SURFACE_RGB },
    columnStyles: {
      0: { cellWidth: 50 },
      1: { cellWidth: 45 },
      2: { cellWidth: 62 },
      3: { cellWidth: 35, halign: 'right' },
      4: { cellWidth: 28 },
      5: { cellWidth: 32 },
    },
    didParseCell(data) {
      if (data.section === 'body' && data.column.index === 4) {
        const client = clients[data.row.index];
        if (client && STATUS_COLOR[client.status]) {
          data.cell.styles.textColor = STATUS_COLOR[client.status];
          data.cell.styles.fontStyle = 'bold';
        }
      }
    },
    margin: { left: 14, right: 14 },
  });

  addPageFooters(doc);
  doc.save(`clients-report-${new Date().toISOString().slice(0, 10)}.pdf`);
}
