export const ROUTES = {
  Login: "/login",
  Admin: "/admin",
  Dashboard: "/",
  Leads: "/leads",
  Contacts: "/contacts",
  Emails: "/emails",
  AIChat: "/chat",
  AISystems: "/systems",
  AISystemDetail: "/systems/:id",
  Analytics: "/analytics",
  Reports: "/reports",
  Support: "/support",
  Billing: "/billing",
  Profile: "/profile",
  Usage: "/usage",
  Team: "/team",
  Settings: "/settings",
} as const;
